#!/usr/bin/env python3
"""
Nexus Aurea 49 CFR Compliance Reference Library — build tool.

The JSON is the source of record. This script renders the Markdown from it.
Never edit the Markdown by hand: run this script instead.

    python3 tools/build_library.py            # render MD from JSON
    python3 tools/build_library.py --check    # verify MD matches JSON, exit 1 if not
"""
import json, sys, hashlib, pathlib

HERE = pathlib.Path(__file__).resolve().parent.parent
JSON_PATH = HERE / "nexus_aurea_cfr_library.json"
MD_PATH = HERE / "nexus-aurea-cfr-library.md"


def h(level, text):
    return f"{'#' * level} {text}\n\n"


def table(headers, rows):
    out = "| " + " | ".join(headers) + " |\n"
    out += "|" + "|".join("---" for _ in headers) + "|\n"
    for r in rows:
        cells = [str(c).replace("|", "\\|").replace("\n", " ") for c in r]
        out += "| " + " | ".join(cells) + " |\n"
    return out + "\n"


def outcomes(d):
    """Render the Pass/Fail/Warning/Unable/NA outcomes of a check dict."""
    labels = [("pass", "✅ Pass"), ("fail", "❌ Fail"), ("warning", "⚠️ Warning"),
              ("unable_to_verify", "❓ Unable to Verify"), ("not_applicable", "➖ Not Applicable")]
    rows = [(lbl, d[key]) for key, lbl in labels if key in d]
    return table(["Outcome", "Criterion"], rows) if rows else ""


def render(d):
    m = d["library_meta"]
    o = h(1, m["name"])
    o += f"**Version:** {m['version']}  |  **Built:** {m['built']}  |  **Last updated:** {m['last_updated']}\n\n"
    o += f"**Authority:** {m['source_authority']}\n\n"
    o += f"**Source URL:** {m['source_url']}\n\n"

    o += "---\n\n"
    o += h(2, "⚠️ RELEASE STATUS")
    o += f"> {m['release_status']}\n\n"
    o += h(2, "⚠️ CITATION VERIFICATION STATUS")
    o += f"> {m['cfr_verification_status']}\n\n"

    o += "---\n\n" + h(2, "SOURCE OF RECORD")
    o += f"{m['source_of_record']}\n\n"
    o += f"- Schema version: `{m['schema_version']}`\n"
    o += f"- Generated by: `tools/build_library.py`\n\n"

    dc = m["document_control"]
    o += "---\n\n" + h(2, "DOCUMENT CONTROL")
    o += table(["Field", "Value"], [
        ("Document number", dc["document_number"]),
        ("Author", dc["author"]),
        ("Technical reviewer", dc["technical_reviewer"]),
        ("Approver", dc["approver"]),
        ("Effective date", dc["effective_date"]),
        ("Review cycle", dc["review_cycle"]),
    ])
    o += h(3, "Change history")
    o += table(["Version", "Date", "Change", "By"],
               [(c["version"], c["date"], c["change"], c["by"]) for c in dc["change_history"]])

    o += "---\n\n" + h(2, "SCOPE")
    o += f"{m['scope']}\n\n"
    o += f"- **Active audit classes:** {', '.join(m['audit_classes_active'])}\n"
    o += f"- **Reference only (do not audit unless requested):** {', '.join(m['audit_classes_reference_only'])}\n\n"

    o += "---\n\n" + h(2, "⚠️ STANDING RULES — NON-NEGOTIABLE")
    for i, r in enumerate(m["standing_rules"], 1):
        o += f"{i}. {r}\n"
    o += "\n"

    o += "---\n\n" + h(2, "OPEN FINDINGS — READ BEFORE USE")
    of = d["open_findings"]
    o += f"{of['preamble']}\n\n"
    o += table(["ID", "Finding", "Status", "Risk", "Blocks release"],
               [(f["id"], f["finding"], f["status"], f["risk"],
                 "YES" if f["blocks_release"] else "no") for f in of["findings"]])
    o += f"*Full detail: {of['detail_reports']}*\n\n"

    o += "---\n\n" + h(2, "⏳ PENDING SOURCES")
    for s in m["pending_sources"]:
        o += f"- {s}\n"
    o += "\n"

    if d.get("pending_checks"):
        o += "---\n\n" + h(2, "⏳ PENDING CHECKS — NOT ACTIVE")
        o += "These checks are written but have no available authority. They must return " \
             "❓ Unable to Verify until their source is integrated. Do not run them as active checks.\n\n"
        for c in d["pending_checks"]:
            o += h(3, f"{c['check_id']} — {c['check']}")
            o += f"**Question:** {c['question']}\n\n"
            o += f"**Blocked on:** {c['blocked_on']}\n\n"

    o += "---\n\n" + h(2, "PARTS")
    for key, p in d["parts"].items():
        o += h(3, p["title"])
        if p.get("url"):
            o += f"Source: {p['url']}\n\n"
        if p.get("citation_verification"):
            o += f"> **Citation status:** {p['citation_verification']}\n\n"
        if p.get("note"):
            o += f"> {p['note']}\n\n"

        if p.get("key_definitions"):
            kd = p["key_definitions"]
            o += h(4, f"Key definitions ({kd['source']})")
            o += table(["Term", "Definition", "Audit relevance"],
                       [(x["term"], x["definition"], x["relevance"]) for x in kd["definitions"]])

        for sec in p.get("sections", []):
            o += h(4, f"{sec['section']} — {sec['title']}")
            if sec.get("rule"):
                o += f"{sec['rule']}\n\n"
            if sec.get("exceptions"):
                o += "**Exceptions:**\n"
                for e in sec["exceptions"]:
                    o += f"- {e}\n"
                o += "\n"
            if sec.get("audit_check"):
                o += outcomes(sec["audit_check"])
            for r in sec.get("rules", []):
                o += f"**`{r['rule_id']}`** — {r['rule']}\n\n"
                o += outcomes(r["audit_check"])
            for el in sec.get("required_elements", []):
                o += h(5, el["element"])
                o += f"- Source: {el['source']}\n- Format: {el['format']}\n\n"
                if el.get("exceptions"):
                    o += "- Exceptions: " + "; ".join(el["exceptions"]) + "\n\n"
                o += outcomes(el["audit_check"])
            if sec.get("sequence_check"):
                sc = sec["sequence_check"]
                o += h(5, "Sequence check")
                o += f"{sc['rule']}\n\n"
                o += f"- ✅ Correct: `{sc['example_correct']}`\n"
                o += f"- ❌ Incorrect: `{sc['example_incorrect']}`\n"
                if sc.get("example_note"):
                    o += f"- {sc['example_note']}\n"
                o += "\n" + outcomes(sc["audit_check"])
            for f in sec.get("additional_fields", []):
                o += h(5, f["field"])
                o += f"{f['rule']}\n\n"
                if f.get("source"):
                    o += f"Source: {f['source']}\n\n"
                o += outcomes(f["audit_check"])
            if sec.get("certification_text_ground"):
                o += h(5, "Required certification language")
                o += f"**Ground:**\n\n> {sec['certification_text_ground']}\n\n"
                o += f"**Air:**\n\n> {sec['certification_text_air']}\n\n"

        if p.get("definition"):
            o += h(4, "Definition")
            dv = p["definition"]
            if isinstance(dv, dict):
                for k, v in dv.items():
                    o += f"- **{k.replace('_', ' ').title()}:** {v}\n"
                o += "\n"
            else:
                o += f"{dv}\n\n"
        if p.get("exceptions_from_class_3"):
            o += h(4, "Exceptions from Class 3")
            o += "> These entries were added in the JSON artifact and have NOT been verified "
            o += "against §173.120(a). Treat as unverified.\n\n"
            for e in p["exceptions_from_class_3"]:
                o += f"- {e}\n"
            o += "\n"
        if p.get("packing_groups"):
            pg = p["packing_groups"]
            o += h(4, f"Packing groups ({pg['source']})")
            if pg.get("warning"):
                o += f"> ⚠️ {pg['warning']}\n\n"
            o += table(["Packing group", "Flash point", "Initial boiling point"],
                       [(g["group"], g["flash_point"], g["initial_boiling_point"]) for g in pg["groups"]])
        if p.get("packing_group_criteria"):
            pgc = p["packing_group_criteria"]
            o += h(4, f"Packing group criteria ({pgc['source']})")
            o += table(["Packing group", "Criteria"],
                       [(g["group"], g["criteria"]) for g in pgc["groups"]])
        if p.get("test_methods_accepted"):
            o += h(4, "Accepted test methods")
            for t in p["test_methods_accepted"]:
                o += f"- {t}\n"
            o += "\n"
        if p.get("test_methods_under_review"):
            tmu = p["test_methods_under_review"]
            o += h(4, "Test methods under review — NOT accepted")
            o += f"> {tmu['note']}\n\n"
            for t in tmu["methods"]:
                o += f"- {t}\n"
            o += "\n"
        if p.get("class_9_includes"):
            o += h(4, "Class 9 subcategories")
            o += table(["Category", "Description", "Source"],
                       [(c["category"], c["description"], c["source"]) for c in p["class_9_includes"]])
        if p.get("common_class_9_materials"):
            o += h(4, "Common Class 9 materials")
            o += table(["Material", "UN number", "Packing group", "Note"],
                       [(c["name"], c["un_number"], c["packing_group"], c["note"])
                        for c in p["common_class_9_materials"]])
        if p.get("relevant_sections"):
            o += h(4, "Relevant sections")
            for s in p["relevant_sections"]:
                o += f"- {s}\n"
            o += "\n"
        if p.get("key_sections"):
            o += h(4, "Key sections")
            for ks in p["key_sections"]:
                o += h(5, f"{ks['section']} — {ks['title']}")
                o += f"{ks['relevance']}\n\n"
                if ks.get("scope_warning"):
                    o += f"> ⚠️ {ks['scope_warning']}\n\n"
                if ks.get("dry_ice_rule"):
                    dr = ks["dry_ice_rule"]
                    o += f"**Rule:** {dr['rule']}\n\n**Source:** {dr['source']}\n\n"
                    o += outcomes(dr["audit_check"])
        for blk in ("air_transport_shipping_paper_requirements", "quantity_per_package_air"):
            if p.get(blk):
                b = p[blk]
                o += h(4, blk.replace("_", " ").title())
                o += f"{b['rule']}\n\n**Source:** {b['source']}\n\n"
                o += outcomes(b["audit_check"])
        if p.get("missing_sections"):
            ms = p["missing_sections"]
            o += h(4, "⚠️ Sections required but NOT YET INTEGRATED")
            o += f"> {ms['note']}\n\n"
            o += table(["Section", "Covers", "Finding"],
                       [(x["section"], x["covers"], x["finding"]) for x in ms["sections"]])
        if p.get("audit_checklist"):
            o += h(4, "Audit checklist")
            for c in p["audit_checklist"]:
                o += h(5, f"{c['check_id']} — {c['check']}")
                o += f"**Question:** {c['question']}\n\n"
                o += outcomes(c)
                if c.get("note"):
                    o += f"*Note: {c['note']}*\n\n"
                o += f"**Source:** {c['source']}\n\n"
                if c.get("source_note"):
                    o += f"> ⚠️ {c['source_note']}\n\n"

    das = d["document_audit_scope"]
    o += "---\n\n" + h(2, das["title"])
    o += table(["Document", "Required for", "Key checks"],
               [(x["doc"], x["required_for"], "; ".join(x["key_checks"])) for x in das["documents"]])

    o += "---\n\n" + h(2, "FINDING STATUS DEFINITIONS")
    o += table(["Status", "Meaning"],
               [(k.replace("_", " "), v) for k, v in d["finding_status_definitions"].items()])

    o += "---\n\n"
    o += f"*{m['footer']}*\n"
    return o


def main():
    d = json.loads(JSON_PATH.read_text())
    md = render(d)
    if "--check" in sys.argv:
        cur = MD_PATH.read_text() if MD_PATH.exists() else ""
        if cur != md:
            print("DRIFT: Markdown does not match JSON. Run tools/build_library.py", file=sys.stderr)
            return 1
        print("OK: Markdown matches JSON (sha256 %s)" % hashlib.sha256(md.encode()).hexdigest()[:16])
        return 0
    MD_PATH.write_text(md)
    print("Wrote %s (%d lines, sha256 %s)" % (MD_PATH.name, md.count("\n"),
                                              hashlib.sha256(md.encode()).hexdigest()[:16]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
